services:
  - type: web
    name: ubuntu-cap-backend
    env: python
    plan: free
    rootDirectory: MYPROJECT/ubuntu-cap-backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn ubuntu_core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

databases:
  - name: ubuntu-cap-db
    plan: free
    databaseName: ubuntu_cap
    user: ubuntu_cap_user
