services: 
  - type: web 
    name: ubuntu-cap-backend 
    env: python 
    plan: free 
    buildCommand: "./build.sh" 
    startCommand: "gunicorn ubuntu_core.wsgi:application" 
    envVars: 
      - key: SECRET_KEY 
        generateValue: true 
      - key: DEBUG 
        value: "False" 
      - key: ALLOWED_HOSTS 
        value: ".onrender.com,localhost,127.0.0.1" 
 
databases: 
  - name: ubuntu-cap-db 
    plan: free 
    databaseName: ubuntu_cap 
    user: ubuntu_cap_user 
